spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/theater_booking
    username: postgres
    password: AhmadSajidSura2003
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
  server:
    port: 8080
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
  cache:
    type: redis
    redis:
      host: localhost
      port: 6379
      timeout: 3s
      lettuce:
        pool:
          max-active: 10
          max-idle: 5
          min-idle: 1